version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"

  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - minio

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - flask-backend
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minio-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - flask-backend

volumes:
  minio_data:
